// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtVyRFbhndOZIdWI_7hsgAUcOsbgkloDc',
    appId: '1:290076135744:web:ce5e2d9a22eedb4ec96aa5',
    messagingSenderId: '290076135744',
    projectId: 'game-mobile-26ab5',
    authDomain: 'game-mobile-26ab5.firebaseapp.com',
    storageBucket: 'game-mobile-26ab5.firebasestorage.app',
    measurementId: 'G-6H4D3XXTZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnMJi5NT_vTC9Pd7vA0AaOIxNRHz6ksl0',
    appId: '1:290076135744:android:e236d9fb7ae9a88dc96aa5',
    messagingSenderId: '290076135744',
    projectId: 'game-mobile-26ab5',
    storageBucket: 'game-mobile-26ab5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV0V77zp5_yogEjpRKH8J-4DrsbjZebkE',
    appId: '1:290076135744:ios:fb4d826adf11298cc96aa5',
    messagingSenderId: '290076135744',
    projectId: 'game-mobile-26ab5',
    storageBucket: 'game-mobile-26ab5.firebasestorage.app',
    iosBundleId: 'com.mycompany.projetogamequiz',
  );
}
